### ISSUE TITLE
Fails on ampersand in `<img>` src

### ISSUE THREAD

**Issue by doublejosh** [HansKre/sanity-plugin-html-to-portable-text#6]
This plugin fails when there is an ampersand (query param) in the src url for an image tag.

FAILS
`<img src="https://img.example.com/photo-123.png?width=100&quality=80">`

FAILS
`<img src="https://img.example.com/photo-123.png&">`

WORKS
`<img src="https://img.example.com/photo-123.png?size=medium">`

WORKS
`<img src="https://img.example.com/photo-123.png">`

**Comment by HansKre** [comment]
@doublejosh thanks for reporting the issue and providing the details for reproduction.
Since I'm not aware of a native image-support of portable-text, would you be fine with the conversion omitting the `img`-tag instead of failing? Or what should be the expected behavior in your opinion?

input: `<p>before</p><img src="https://img.example.com/photo-123.png?width=100&quality=80"><p>after</p>`

result:
<img width="623" alt="image" src="https://user-images.githubusercontent.com/7346919/179391247-7c348fb3-773a-45f5-a661-948b614d500b.png">

**Comment by doublejosh** [comment]
We use this module to ingest migrated content, and allow pasting HTML content so there was plenty of images in into.

Nice!

**Comment by HansKre** [comment]
Glad to hear. It is available in latest release. Please let me know if this issue can be closed.
